/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitRouteImport } from './routes/visit'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as NewsRouteImport } from './routes/news'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcademicsRouteImport } from './routes/academics'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AcademicsIndexRouteImport } from './routes/academics.index'
import { Route as PortalTuitionFeesRouteImport } from './routes/portal.tuition-fees'
import { Route as PortalTeacherListRouteImport } from './routes/portal.teacher-list'
import { Route as PortalStudentListRouteImport } from './routes/portal.student-list'
import { Route as PortalIndividualResultRouteImport } from './routes/portal.individual-result'
import { Route as PortalFormDownloadRouteImport } from './routes/portal.form-download'
import { Route as PortalFacilitiesRouteImport } from './routes/portal.facilities'
import { Route as PortalExamRoutineRouteImport } from './routes/portal.exam-routine'
import { Route as PortalClassRoutineRouteImport } from './routes/portal.class-routine'
import { Route as PortalArchiveRouteImport } from './routes/portal.archive'
import { Route as AdminTeachersRouteImport } from './routes/admin.teachers'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminResultsRouteImport } from './routes/admin.results'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminFormsRouteImport } from './routes/admin.forms'
import { Route as AdminFeesRouteImport } from './routes/admin.fees'
import { Route as AdminExamsRouteImport } from './routes/admin.exams'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminClassesRouteImport } from './routes/admin.classes'
import { Route as AdminAdmissionsRouteImport } from './routes/admin.admissions'
import { Route as AcademicsSlugRouteImport } from './routes/academics.$slug'

const VisitRoute = VisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsRoute = AcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AcademicsIndexRoute = AcademicsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcademicsRoute,
} as any)
const PortalTuitionFeesRoute = PortalTuitionFeesRouteImport.update({
  id: '/tuition-fees',
  path: '/tuition-fees',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTeacherListRoute = PortalTeacherListRouteImport.update({
  id: '/teacher-list',
  path: '/teacher-list',
  getParentRoute: () => PortalRoute,
} as any)
const PortalStudentListRoute = PortalStudentListRouteImport.update({
  id: '/student-list',
  path: '/student-list',
  getParentRoute: () => PortalRoute,
} as any)
const PortalIndividualResultRoute = PortalIndividualResultRouteImport.update({
  id: '/individual-result',
  path: '/individual-result',
  getParentRoute: () => PortalRoute,
} as any)
const PortalFormDownloadRoute = PortalFormDownloadRouteImport.update({
  id: '/form-download',
  path: '/form-download',
  getParentRoute: () => PortalRoute,
} as any)
const PortalFacilitiesRoute = PortalFacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => PortalRoute,
} as any)
const PortalExamRoutineRoute = PortalExamRoutineRouteImport.update({
  id: '/exam-routine',
  path: '/exam-routine',
  getParentRoute: () => PortalRoute,
} as any)
const PortalClassRoutineRoute = PortalClassRoutineRouteImport.update({
  id: '/class-routine',
  path: '/class-routine',
  getParentRoute: () => PortalRoute,
} as any)
const PortalArchiveRoute = PortalArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => PortalRoute,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResultsRoute = AdminResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFormsRoute = AdminFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeesRoute = AdminFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExamsRoute = AdminExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClassesRoute = AdminClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdmissionsRoute = AdminAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => AdminRoute,
} as any)
const AcademicsSlugRoute = AcademicsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AcademicsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/portal': typeof PortalRouteWithChildren
  '/visit': typeof VisitRoute
  '/academics/$slug': typeof AcademicsSlugRoute
  '/admin/admissions': typeof AdminAdmissionsRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/portal/archive': typeof PortalArchiveRoute
  '/portal/class-routine': typeof PortalClassRoutineRoute
  '/portal/exam-routine': typeof PortalExamRoutineRoute
  '/portal/facilities': typeof PortalFacilitiesRoute
  '/portal/form-download': typeof PortalFormDownloadRoute
  '/portal/individual-result': typeof PortalIndividualResultRoute
  '/portal/student-list': typeof PortalStudentListRoute
  '/portal/teacher-list': typeof PortalTeacherListRoute
  '/portal/tuition-fees': typeof PortalTuitionFeesRoute
  '/academics/': typeof AcademicsIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/visit': typeof VisitRoute
  '/academics/$slug': typeof AcademicsSlugRoute
  '/admin/admissions': typeof AdminAdmissionsRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/portal/archive': typeof PortalArchiveRoute
  '/portal/class-routine': typeof PortalClassRoutineRoute
  '/portal/exam-routine': typeof PortalExamRoutineRoute
  '/portal/facilities': typeof PortalFacilitiesRoute
  '/portal/form-download': typeof PortalFormDownloadRoute
  '/portal/individual-result': typeof PortalIndividualResultRoute
  '/portal/student-list': typeof PortalStudentListRoute
  '/portal/teacher-list': typeof PortalTeacherListRoute
  '/portal/tuition-fees': typeof PortalTuitionFeesRoute
  '/academics': typeof AcademicsIndexRoute
  '/admin': typeof AdminIndexRoute
  '/portal': typeof PortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/portal': typeof PortalRouteWithChildren
  '/visit': typeof VisitRoute
  '/academics/$slug': typeof AcademicsSlugRoute
  '/admin/admissions': typeof AdminAdmissionsRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/forms': typeof AdminFormsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/portal/archive': typeof PortalArchiveRoute
  '/portal/class-routine': typeof PortalClassRoutineRoute
  '/portal/exam-routine': typeof PortalExamRoutineRoute
  '/portal/facilities': typeof PortalFacilitiesRoute
  '/portal/form-download': typeof PortalFormDownloadRoute
  '/portal/individual-result': typeof PortalIndividualResultRoute
  '/portal/student-list': typeof PortalStudentListRoute
  '/portal/teacher-list': typeof PortalTeacherListRoute
  '/portal/tuition-fees': typeof PortalTuitionFeesRoute
  '/academics/': typeof AcademicsIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academics'
    | '/admin'
    | '/admissions'
    | '/contact'
    | '/gallery'
    | '/news'
    | '/portal'
    | '/visit'
    | '/academics/$slug'
    | '/admin/admissions'
    | '/admin/classes'
    | '/admin/events'
    | '/admin/exams'
    | '/admin/fees'
    | '/admin/forms'
    | '/admin/gallery'
    | '/admin/results'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/teachers'
    | '/portal/archive'
    | '/portal/class-routine'
    | '/portal/exam-routine'
    | '/portal/facilities'
    | '/portal/form-download'
    | '/portal/individual-result'
    | '/portal/student-list'
    | '/portal/teacher-list'
    | '/portal/tuition-fees'
    | '/academics/'
    | '/admin/'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admissions'
    | '/contact'
    | '/gallery'
    | '/news'
    | '/visit'
    | '/academics/$slug'
    | '/admin/admissions'
    | '/admin/classes'
    | '/admin/events'
    | '/admin/exams'
    | '/admin/fees'
    | '/admin/forms'
    | '/admin/gallery'
    | '/admin/results'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/teachers'
    | '/portal/archive'
    | '/portal/class-routine'
    | '/portal/exam-routine'
    | '/portal/facilities'
    | '/portal/form-download'
    | '/portal/individual-result'
    | '/portal/student-list'
    | '/portal/teacher-list'
    | '/portal/tuition-fees'
    | '/academics'
    | '/admin'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academics'
    | '/admin'
    | '/admissions'
    | '/contact'
    | '/gallery'
    | '/news'
    | '/portal'
    | '/visit'
    | '/academics/$slug'
    | '/admin/admissions'
    | '/admin/classes'
    | '/admin/events'
    | '/admin/exams'
    | '/admin/fees'
    | '/admin/forms'
    | '/admin/gallery'
    | '/admin/results'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/teachers'
    | '/portal/archive'
    | '/portal/class-routine'
    | '/portal/exam-routine'
    | '/portal/facilities'
    | '/portal/form-download'
    | '/portal/individual-result'
    | '/portal/student-list'
    | '/portal/teacher-list'
    | '/portal/tuition-fees'
    | '/academics/'
    | '/admin/'
    | '/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademicsRoute: typeof AcademicsRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AdmissionsRoute: typeof AdmissionsRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  NewsRoute: typeof NewsRoute
  PortalRoute: typeof PortalRouteWithChildren
  VisitRoute: typeof VisitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics': {
      id: '/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/academics/': {
      id: '/academics/'
      path: '/'
      fullPath: '/academics/'
      preLoaderRoute: typeof AcademicsIndexRouteImport
      parentRoute: typeof AcademicsRoute
    }
    '/portal/tuition-fees': {
      id: '/portal/tuition-fees'
      path: '/tuition-fees'
      fullPath: '/portal/tuition-fees'
      preLoaderRoute: typeof PortalTuitionFeesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/teacher-list': {
      id: '/portal/teacher-list'
      path: '/teacher-list'
      fullPath: '/portal/teacher-list'
      preLoaderRoute: typeof PortalTeacherListRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/student-list': {
      id: '/portal/student-list'
      path: '/student-list'
      fullPath: '/portal/student-list'
      preLoaderRoute: typeof PortalStudentListRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/individual-result': {
      id: '/portal/individual-result'
      path: '/individual-result'
      fullPath: '/portal/individual-result'
      preLoaderRoute: typeof PortalIndividualResultRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/form-download': {
      id: '/portal/form-download'
      path: '/form-download'
      fullPath: '/portal/form-download'
      preLoaderRoute: typeof PortalFormDownloadRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/facilities': {
      id: '/portal/facilities'
      path: '/facilities'
      fullPath: '/portal/facilities'
      preLoaderRoute: typeof PortalFacilitiesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/exam-routine': {
      id: '/portal/exam-routine'
      path: '/exam-routine'
      fullPath: '/portal/exam-routine'
      preLoaderRoute: typeof PortalExamRoutineRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/class-routine': {
      id: '/portal/class-routine'
      path: '/class-routine'
      fullPath: '/portal/class-routine'
      preLoaderRoute: typeof PortalClassRoutineRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/archive': {
      id: '/portal/archive'
      path: '/archive'
      fullPath: '/portal/archive'
      preLoaderRoute: typeof PortalArchiveRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/results': {
      id: '/admin/results'
      path: '/results'
      fullPath: '/admin/results'
      preLoaderRoute: typeof AdminResultsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forms': {
      id: '/admin/forms'
      path: '/forms'
      fullPath: '/admin/forms'
      preLoaderRoute: typeof AdminFormsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fees': {
      id: '/admin/fees'
      path: '/fees'
      fullPath: '/admin/fees'
      preLoaderRoute: typeof AdminFeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exams': {
      id: '/admin/exams'
      path: '/exams'
      fullPath: '/admin/exams'
      preLoaderRoute: typeof AdminExamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/classes': {
      id: '/admin/classes'
      path: '/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AdminClassesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admissions': {
      id: '/admin/admissions'
      path: '/admissions'
      fullPath: '/admin/admissions'
      preLoaderRoute: typeof AdminAdmissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/academics/$slug': {
      id: '/academics/$slug'
      path: '/$slug'
      fullPath: '/academics/$slug'
      preLoaderRoute: typeof AcademicsSlugRouteImport
      parentRoute: typeof AcademicsRoute
    }
  }
}

interface AcademicsRouteChildren {
  AcademicsSlugRoute: typeof AcademicsSlugRoute
  AcademicsIndexRoute: typeof AcademicsIndexRoute
}

const AcademicsRouteChildren: AcademicsRouteChildren = {
  AcademicsSlugRoute: AcademicsSlugRoute,
  AcademicsIndexRoute: AcademicsIndexRoute,
}

const AcademicsRouteWithChildren = AcademicsRoute._addFileChildren(
  AcademicsRouteChildren,
)

interface AdminRouteChildren {
  AdminAdmissionsRoute: typeof AdminAdmissionsRoute
  AdminClassesRoute: typeof AdminClassesRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminExamsRoute: typeof AdminExamsRoute
  AdminFeesRoute: typeof AdminFeesRoute
  AdminFormsRoute: typeof AdminFormsRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminResultsRoute: typeof AdminResultsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTeachersRoute: typeof AdminTeachersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdmissionsRoute: AdminAdmissionsRoute,
  AdminClassesRoute: AdminClassesRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminExamsRoute: AdminExamsRoute,
  AdminFeesRoute: AdminFeesRoute,
  AdminFormsRoute: AdminFormsRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminResultsRoute: AdminResultsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTeachersRoute: AdminTeachersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PortalRouteChildren {
  PortalArchiveRoute: typeof PortalArchiveRoute
  PortalClassRoutineRoute: typeof PortalClassRoutineRoute
  PortalExamRoutineRoute: typeof PortalExamRoutineRoute
  PortalFacilitiesRoute: typeof PortalFacilitiesRoute
  PortalFormDownloadRoute: typeof PortalFormDownloadRoute
  PortalIndividualResultRoute: typeof PortalIndividualResultRoute
  PortalStudentListRoute: typeof PortalStudentListRoute
  PortalTeacherListRoute: typeof PortalTeacherListRoute
  PortalTuitionFeesRoute: typeof PortalTuitionFeesRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalArchiveRoute: PortalArchiveRoute,
  PortalClassRoutineRoute: PortalClassRoutineRoute,
  PortalExamRoutineRoute: PortalExamRoutineRoute,
  PortalFacilitiesRoute: PortalFacilitiesRoute,
  PortalFormDownloadRoute: PortalFormDownloadRoute,
  PortalIndividualResultRoute: PortalIndividualResultRoute,
  PortalStudentListRoute: PortalStudentListRoute,
  PortalTeacherListRoute: PortalTeacherListRoute,
  PortalTuitionFeesRoute: PortalTuitionFeesRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademicsRoute: AcademicsRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AdmissionsRoute: AdmissionsRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  NewsRoute: NewsRoute,
  PortalRoute: PortalRouteWithChildren,
  VisitRoute: VisitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
